---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app:
      demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8020
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: glebkr/spring-demo
          ports:
            - containerPort: 8020
          livenessProbe:
            httpGet:
              path: /health
              port: 8020
            initialDelaySeconds: 30
            timeoutSeconds: 1