services:
  postgres:
    container_name: spring-postgres
    image: postgres
    environment:
      POSTGRES_USER: gleb
      POSTGRES_PASSWORD: password
      PGDATA: /data/spring-postgres
    volumes:
      - postgres:/data/spring-postgres
    ports:
      - "5555:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: