services:
  postgres:
    container_name: spring-postgres
    image: postgres
    environment:
      POSTGRES_USER: gleb
      POSTGRES_PASSWORD: password
      PGDATA: /data/spring-postgres
    volumes:
      - postgres:/data/spring-postgres
    ports:
      - "5555:5432"
    networks:
      - postgres
    restart: unless-stopped
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

networks:
  postgres:
    driver: bridge

volumes:
  postgres: